### ISSUE TITLE
Handle no .dullfile error more gracefully

### ISSUE THREAD

**Issue by tivac** [tivac/dullard#113]
Currently you get a really gross stack trace.

```
C:\Users\kriss
λ dullard
info default build complete in 0.001 seconds
ERR! cli Build failed!
ERR! cli Error: Unknown task: default
ERR! cli     at Object.assign._runTask.name [as _runTask] (C:\Users\kriss\AppData\Roaming\npm\node_modules\dullard\src\dullard.js:131:19)
ERR! cli     at C:\Users\kriss\AppData\Roaming\npm\node_modules\dullard\node_modules\p-each-series\index.js:4:73
ERR! cli     at C:\Users\kriss\AppData\Roaming\npm\node_modules\dullard\node_modules\p-reduce\index.js:16:10
ERR! cli     at process._tickCallback (node.js:406:9)
ERR! cli     at Function.Module.runMain (module.js:449:11)
ERR! cli     at startup (node.js:141:18)
ERR! cli     at node.js:933:3
ERR! cli  [Error: Unknown task: default]
```

which isn't useful 🤢

**Comment by tivac** [comment]
Fixed in v4.0.0
